[package]
name = "pedersencommit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = "3"
rand = "0.8.4"
rand_core = "0.5.0"
office = "0.8.1"
colored = "2.0.0"

